AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for
  running Kittens Carousel Static Website on EC2.
  Kittens Carousel Static Website will be
  deployed on Amazon Linux 2023 EC2 Instance with custom 
  security group which allows http connections on port 80 
  and ssh port 22 from anywhere. Kittens Carousel Static 
  Website is downloaded from my Public Github repository,
  then deployed on Apache Web Server.
# Parameters:
#   LatestAmiId:
#     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
Resources:
  KittenCarouselProject:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c647eace872fc02
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups: 
        - !Ref ProjectSecGrp
      Tags: 
        - Key: Name
          Value: !Sub Turan ${AWS::StackName}
      UserData: 
        Fn::Base64: !Sub |
            #! /bin/bash
            sudo dnf update -y
            sudo dnf install httpd -y
            cd /var/www/html/
            sudo chmod -R 777 /var/www/html/
            FLDR=https://raw.githubusercontent.com/turangozukara/Kitten-Carousel/main/101-kittens-carousel-static-website-ec2/static-web/
            wget $FLDR/cat0.jpg
            wget $FLDR/cat1.jpg
            wget $FLDR/cat2.jpg
            wget $FLDR/index.html
            sudo systemctl start httpd
            sudo systemctl enable httpd
  ProjectSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "This security group enables SSH and HTTP protocols." # Required
      GroupName: "Kitten-Carousel-Sec-Grp"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: env
          Value: dev

Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt KittenCarouselProject.PublicDnsName
